# Generated by Django 4.1.3 on 2022-11-29 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_alter_car_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carPhoto',
            field=models.ImageField(blank=True, upload_to='images/carImages'),
        ),
        migrations.AlterField(
            model_name='car',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
