# Generated by Django 3.1.14 on 2022-12-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_order_cost_order_latitude_order_longitude_order_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
