# Generated by Django 3.1.14 on 2023-01-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_auto_20230101_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='car',
        ),
        migrations.RemoveField(
            model_name='call',
            name='customer',
        ),
        migrations.AlterField(
            model_name='call',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
