# Generated by Django 3.1.14 on 2023-01-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_auto_20230104_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
    ]
