# Generated by Django 3.1.14 on 2023-01-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_auto_20230104_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.CharField(default='waiting...', editable=False, max_length=20, null=True),
        ),
    ]
