# Generated by Django 4.1.3 on 2022-11-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_age_customuser_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='carColor',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='carModel',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='carNumber',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
