# Generated by Django 4.1.3 on 2022-12-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='carModel',
            new_name='shahar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='carColor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='carNumber',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='clientimages/'),
        ),
    ]
