# Generated by Django 3.1.14 on 2023-01-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230117_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
