# Generated by Django 3.1.14 on 2023-01-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washers', '0002_auto_20230102_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drive',
        ),
    ]
