# Generated by Django 3.1.14 on 2023-01-02 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0019_auto_20230101_1546'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('washers', '0003_delete_drive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ishchi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('ordered_by', models.CharField(max_length=50, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.order')),
            ],
        ),
    ]
