# Generated by Django 3.1.14 on 2023-01-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washers', '0005_auto_20230102_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_cart_order',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='driver_cart_order',
            name='latitude',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver_cart_order',
            name='longitude',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver_cart_order',
            name='part',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver_cart_order',
            name='paytype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
