# Generated by Django 3.1.14 on 2023-01-04 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_auto_20230104_1657'),
        ('washers', '0006_auto_20230104_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_cart_order',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='driver_cart_order',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='driver_cart_order',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.order'),
        ),
    ]
