# Generated by Django 3.1.14 on 2023-01-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washers', '0009_driver_cart_order_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_cart_order',
            name='order',
        ),
        migrations.RemoveField(
            model_name='driver_cart_order',
            name='transaction_id',
        ),
    ]
