# Generated by Django 3.1.14 on 2023-01-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washers', '0010_auto_20230105_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_cart_order',
            name='ordered_by',
        ),
    ]
