# Generated by Django 3.1.14 on 2023-01-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washers', '0011_remove_driver_cart_order_ordered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_cart_order',
            name='ordered_by',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='driver_cart_order',
            name='service',
            field=models.CharField(choices=[('PD', 'pending'), ('FN', 'finished')], default='PD', max_length=20, null=True),
        ),
    ]
