# Generated by Django 3.1.14 on 2023-01-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washers', '0012_auto_20230109_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_cart_order',
            name='service',
            field=models.CharField(choices=[('pending', 'pending'), ('finished', 'finished')], default='pending', max_length=20, null=True),
        ),
    ]
